version: "3"
services:
  bot:
    image: "dggua/oicq_bot"
    ports:
      - "{port1}:8080" # http request
      - "{port2}:8081" # ws request
    volumes:
      - /home/ubuntu/.oicq:/app/data
    restart: always
    command: 123123123123
