version: "3"
services:
  bot:
    build: "."
    ports:
      - "{port1}:8080" # http request
      - "{port2}:8081" # ws request
    volumes:
      - /home/ubuntu/.oicq:/app/data
    restart: always
    command: {qq} {password}
