name: run project # workflow名
on:
  push:
    branches:
      - main
jobs: # 各个作业
  Dockerize:
    runs-on: ubuntu-latest # 运行环境
    steps: # 作业的各个步骤
      - uses: actions/checkout@v3 # git pull
      - name: Login Docker
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker
        run: |
          docker build --platform linux/amd64 -t dglog-backend:latest  .
          docker tag dglog-backend:latest ${{ secrets.DOCKER_REPOSITORY }}
      - name: Push Docker
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}
